= Challenge: [RHEL-CTF01]

== The Story

You've walked in to the office, and barely feel the warmth of your first mug of coffee when your boss, **Scott**, calmly walks up to you.

[quote, Scott]
____
Yeah, so look, theres a problem.  You were out yesterday, and... you know, I _couldn't_ bother you because of that pesky company policy thing...  Anyway, you know before being a manager, I did the same work as you, so I handled a few things for you.  You're welcome!
____

He goes on to tell you that he setup some sudo rights for the web guys.  

[quote, Scott]
____
"They just want to be able to manage httpd.  Must be on some kinda power trip over there in the web group."
____

**Scott** got started on one in `/etc/sudoers.d/webteam-sudo` but..well.. Contrary to his belief, it's not working.

**The Problem:** Scott tried to edit a file in `/etc/sudoers.d/webteam-sudo`, but he made a mistake. Now, the `webteam` user can't do their job.

== Your Challenge

Can you fix his sudoers drop-in so that it let's the "webteam" user restart (and otherwise manage) httpd via systemd?

* **Target File:** `/etc/sudoers.d/webteam-sudo`
* **The Goal:** Allow the user `webteam` to use `sudo` for `systemctl` commands.
* **The Catch:** They should be able to start, stop, and restart the `httpd` service **without** typing a password.

=== Helpful Info
[cols="1,1"]
|===
|Username |Password

|webteam
|redhat
|===

---
**Lab Developers:**

* smcbrien@redhat.com
* nlager@redhat.com